-- MySQL Script generated by MySQL Workbench
-- Sat Jun 16 12:59:59 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `idPessoa` INT(4) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NULL,
  `email` VARCHAR(45) NULL,
  `telefone` INT(20) NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Processos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Processos` (
  `numeroProcesso` VARCHAR(7) NOT NULL,
  `tipoProcesso` VARCHAR(4) NULL,
  `Pessoa_idPessoa` INT(4) NOT NULL,
  PRIMARY KEY (`numeroProcesso`, `Pessoa_idPessoa`),
  INDEX `fk_Processos_Pessoa_idx` (`Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_Processos_Pessoa`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evento` (
  `idEvento` INT(4) NOT NULL,
  `dataEvento` INT(6) NULL,
  `horaEvento` INT(4) NULL,
  `descEvento` VARCHAR(30) NULL,
  `Processos_numeroProcesso` VARCHAR(7) NOT NULL,
  `Processos_Pessoa_idPessoa` INT(4) NOT NULL,
  PRIMARY KEY (`idEvento`),
  INDEX `fk_evento_Processos1_idx` (`Processos_numeroProcesso` ASC, `Processos_Pessoa_idPessoa` ASC),
  CONSTRAINT `fk_evento_Processos1`
    FOREIGN KEY (`Processos_numeroProcesso` , `Processos_Pessoa_idPessoa`)
    REFERENCES `mydb`.`Processos` (`numeroProcesso` , `Pessoa_idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
